import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Topheader from "../components/topHeader/page"
import Header from "@/components/header/page";
import Future from "@/components/future/page";
import Category from "@/components/category/page";
import Offer from "@/components/Offer/page";
import TrandyProduct from "@/components/TrandyProduct/page";
import NewProduct from "@/components/newProduct/page";
import Subscribe from "@/components/Subscribe/page";
import Footer from "@/components/Footer/page";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet" />
        <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" />
        <link href="css/style.css" rel="stylesheet" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Topheader/>
        <Header/>
        <Future/>
        <Category/>
        <Offer/>
        <TrandyProduct/>
        <Subscribe/>
        <NewProduct/>

        <Footer/>
        {children}

        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="lib/easing/easing.min.js"></script>
        <script src="lib/owlcarousel/owl.carousel.min.js"></script>
        <script src="mail/jqBootstrapValidation.min.js"></script>
        <script src="mail/contact.js"></script>
        <script src="js/main.js"></script>
      </body>

    </html>
  );
}
